# Generated by Django 3.2 on 2021-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('class_object', models.CharField(max_length=150, verbose_name='Класс')),
                ('description', models.TextField(verbose_name='Описание обьекта')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
    ]
