# Generated by Django 3.2 on 2021-06-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_car', models.CharField(max_length=40, verbose_name='Категория')),
                ('status_active', models.BooleanField()),
                ('description', models.TextField(verbose_name='Описание авто')),
            ],
        ),
    ]
